### ISSUE TITLE
1.8.9 1.0.0 Crash on Server

### ISSUE THREAD

**Issue by Rohzek** [Lilylicious/ThaumicEquivalence#19] opened 2017-02-04 08:48 UTC
Reports that net.minecraft.block.Block.func_149666_a isn't defined.
Full crashlog here:
http://pastebin.com/7i6VSpNB

**Comment by Lilylicious** [comment] 2017-02-04 09:19
I know what the problem is, but won't be able to fix until Monday

**Comment by Lilylicious** [comment] 2017-02-05 17:11
Fixed in 1.0.1

**Closed as completed by Lilylicious** 2017-02-05 17:11 UTC
