### ISSUE TITLE
Unable to add vis EMC values in worlds with missing item IDs

### ISSUE THREAD

**Issue by Revemohl** [Lilylicious/ThaumicEquivalence#9] opened 2015-10-15 22:50 UTC
This is something that's been happening to me for a while, and I think I finally tracked its cause.
If you remove a mod that has items with EMC values from your pack (and you have knowledge of those items in your tablet), upon booting up a map you get messages like this on your console:

> [Client thread/INFO] [ProjectE]: Failed to cache knowledge for id:4114 damage:0 qnty:1: java.lang.NullPointerException

It looks like when that happens, ThaumicEquivalence's mapper fails to assign EMC points for vis, resulting in things like even the basic Arcane Stone not getting an EMC value assigned to it. It also looks like adding those missing mods back into your pack makes the mapper behave once again.

**Comment by Lilylicious** [comment] 2015-10-15 23:03
Interesting. I'll see if I can't get a fix out tomorrow.

**Comment by MaPePeR** [comment] 2015-10-16 12:05
I _think_ this is kind of a duplicate of #7. If you enable pregenerated EMC in ProjectE you will probably see the same Crash.

Its a bug in ProjectE that is fixed by sinkillerj/ProjectE#1046 and can be circumvented by not using the Object-Variant of the `registerEMC`-Method for `Block` or `Item`, but using the `ItemStack`-variant.

_Edit:_ Actually it might not only be the `registerEMC`-Method, but all the `addConversion`-Methods as well.

@Revemohl Could you try [this](https://github.com/MaPePeR/ProjectE/releases/tag/v1.9.3h-uniqueItemNamesInsteadIds) version of ProjectE and see if it fixes the problem?

**Comment by Lilylicious** [comment] 2015-10-16 12:07
I'm pretty sure I only use itemstacks though.

**Comment by Revemohl** [comment] 2015-10-16 13:51
@MaPePeR Just tried it out and it seems to have worked about as perfectly as playing for 5 minutes lets you verify, none of those messages I mentioned showed up when loading my world and arcane stone now has an EMC value in there.

**Comment by Lilylicious** [comment] 2018-05-12 13:24
Closing issue due to narrowing of scope in newer versions.

**Closed as completed by Lilylicious** 2018-05-12 13:24 UTC
